# Generated by Django 3.2.7 on 2021-09-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('episodio', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('texto_apertura', models.TextField(max_length=1000)),
                ('director', models.CharField(max_length=120)),
                ('productor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pelicula',
                'ordering': ['episodio'],
            },
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('diametro', models.PositiveIntegerField(default=100)),
                ('poblacion', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Planeta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('peliculas', models.ManyToManyField(default=[], related_name='personaje_peliculas', to='api.Pelicula')),
            ],
            options={
                'verbose_name': 'Personaje',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='planetas',
            field=models.ManyToManyField(related_name='pelicula_planetas', to='api.Planeta', verbose_name='Planetas'),
        ),
    ]
