# Generated by Django 3.2.7 on 2021-09-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='episodio',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
